BATCH_SIZE = 32;
NUM_READING_THREADS = 4;

Input={
	"BATCH_SIZE":			32;
	"NUM_THREADS":			4;
	"MIN_AFTER_DEQUEUE":	200;
	"CAPACITY":				0;
}

Input["CAPACITY"] = Input["MIN_AFTER_DEQUEUE"]+Input["BATCH_SIZE"]*3;

Model={
	"WEIGHT_INIT_STD":		0.01;
	"DROP_OUT_KEEP_PROB":	0.9;
	"REG_RATE":				0.01;
}